CREATE DATABASE UsersDB;
CREATE TABLE UsersDB.Users (ID int AUTO_INCREMENT NOT NULL, login VARCHAR(30) NOT NULL, password varchar(40) NOT NULL, PRIMARY KEY(ID));
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON UsersDB.* TO 'admin'@'%';